# Generated by Django 5.1.4 on 2025-01-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('endereço', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=26)),
            ],
        ),
    ]
